name: Build buil from global workflow Application

on:
  workflow_dispatch:
  
  push:
    branches:
      - none

jobs:
  build:
    uses: ravindra639/POC/.github/workflows/dotnet-build.yml@master
    with:
      dotnet-version: "10.0"
